% Initialize model inputs
exampleHelperCreateBehaviorModelInputs

% Define the initial start pose of the vehicle in the scene:
start = [267.5 441.5 -pi/2];
goal  = [950 1000 0];

% Set max edge length
maxElementPerEdge = 25;

% Configure service messages
matType = coder.typeof(int8(0),[1201 1201],[1 1]);
refPathType = coder.typeof(0,[maxRefPathLen 3],[1 0]);
pathBusType = coder.typeof(struct('PointList',coder.typeof(0,[100000 2],[1 0]),...
    'PathIndices',coder.typeof(0,[1000 2],[1 0]),...
    'NumPath',0));
inMsg = struct(...
    'TuneableTerrainAwareParams',tuneableTerrainAwareParams, ...
    'PathList',pathBusType, ...
    'GlobalMat',matType,...
    'GridLoc',gridLoc, ...
    'Resolution',res, ...
    'StartPose',start,...
    'GoalPose',goal);
outMsg = struct('RefPath',refPathType);

% Generate service and all required message types
sType = [coder.typeof(inMsg) coder.typeof(outMsg)];
msgDir = fullfile(matlab.project.rootProject().RootFolder,'ROSHelper');
ros2msgfromstruct(sType,Folder=msgDir,PkgName="offroad_msg",...
    Name="PlanRoute",Type="srv");